// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPaanp0k803CJB08aI0cajCltRPakV55Q',
    appId: '1:193013043836:web:ede39c96ec704f07cdeff9',
    messagingSenderId: '193013043836',
    projectId: 'books-app-e2157',
    authDomain: 'books-app-e2157.firebaseapp.com',
    storageBucket: 'books-app-e2157.firebasestorage.app',
    measurementId: 'G-RWJMMZXW0L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf6WHS5Jf6l10o70PGJ9hdWRYaLRCCJcg',
    appId: '1:193013043836:android:c163f52646cd35c3cdeff9',
    messagingSenderId: '193013043836',
    projectId: 'books-app-e2157',
    storageBucket: 'books-app-e2157.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqlIr2qHeeugdU4RhwYgCX88raMn4GYTA',
    appId: '1:193013043836:ios:b6d87f7e72a2436ccdeff9',
    messagingSenderId: '193013043836',
    projectId: 'books-app-e2157',
    storageBucket: 'books-app-e2157.firebasestorage.app',
    iosBundleId: 'com.example.booksApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqlIr2qHeeugdU4RhwYgCX88raMn4GYTA',
    appId: '1:193013043836:ios:b6d87f7e72a2436ccdeff9',
    messagingSenderId: '193013043836',
    projectId: 'books-app-e2157',
    storageBucket: 'books-app-e2157.firebasestorage.app',
    iosBundleId: 'com.example.booksApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPaanp0k803CJB08aI0cajCltRPakV55Q',
    appId: '1:193013043836:web:6b1a2c82b18a1badcdeff9',
    messagingSenderId: '193013043836',
    projectId: 'books-app-e2157',
    authDomain: 'books-app-e2157.firebaseapp.com',
    storageBucket: 'books-app-e2157.firebasestorage.app',
    measurementId: 'G-2BE6CC9CPQ',
  );
}
